### ISSUE TITLE
Pip meld error on supervisor start

### ISSUE THREAD

**Issue by fullmooninu** [ajcrowe/puppet-supervisord#80]
Error from agent run (relevant part seems to be python meld3 error)

```
09/12/15 14:52:46 elias@honshuu-api-lb2.wdc.sl ~: sudo puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: You need the `newrelic_rpm` gem. sudo /opt/puppet/bin/gem install newrelic_rpm
Info: Caching catalog for honshuu-api-lb2.wdc.sl
Warning: /Apt_key[Add key: C43C79AD from Apt::Source logentries]: The id should be a full fingerprint (40 characters), see README.
Info: Applying configuration version '1449672774'
Error: Could not start Service[supervisord]: Execution of '/etc/init.d/supervisord start' returned 1: Starting supervisor: Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5
Error: /Stage[main]/Supervisord::Service/Service[supervisord]/ensure: change from stopped to running failed: Could not start Service[supervisord]: Execution of '/etc/init.d/supervisord start' returned 1: Starting supervisor: Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5
Notice: /Stage[main]/Supervisord/Anchor[supervisord::end]: Dependency Service[supervisord] has failures: true
Warning: /Stage[main]/Supervisord/Anchor[supervisord::end]: Skipping because of failed dependencies
Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]: Dependency Service[supervisord] has failures: true
Warning: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]: Skipping because of failed dependencies
Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]: Dependency Service[supervisord] has failures: true
Warning: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]: Skipping because of failed dependencies
Notice: /Stage[main]/Site::Api/Supervisord::Supervisorctl[restart_api]/Exec[supervisorctl_command_restart_api]: Dependency Service[supervisord] has failures: true
Warning: /Stage[main]/Site::Api/Supervisord::Supervisorctl[restart_api]/Exec[supervisorctl_command_restart_api]: Skipping because of failed dependencies
Notice: Finished catalog run in 9.87 seconds
```

Supervisor start error
```
 ~: sudo service supervisord start 
Starting supervisor: Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5
```

list of pip modules
```
 ~: pip freeze
apt-xapian-index==0.44
chardet==2.0.1
command-not-found==0.2.44
GnuPGInterface==0.3.2
language-selector==0.1
meld3==1.0.2
psutil==0.4.1
pycurl==7.19.0
python-apt===0.8.3ubuntu7.3
python-debian===0.1.21ubuntu1
setproctitle==1.0.1
simplejson==2.3.2
supervisor==3.2.0
ufw==0.31.1.post1
unattended-upgrades==0.1
/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

puppet modules
```
/etc/puppetlabs/puppet/modules
├── ajcrowe-supervisord (v0.5.2)
├── deric-storm (v0.3.0)
├── deric-zookeeper (v0.3.9)
├── dwerder-graphite (v5.14.0)
├── jfryman-nginx (v0.2.7)
├── joshcooper-powershell (v0.0.6)
├── kafka (???)
├── maestrodev-statsd (v1.0.4)
├── puppetlabs-apt (v1.8.0)
├── puppetlabs-concat (v1.2.2)
├── puppetlabs-inifile (v1.2.0)
├── puppetlabs-java (v1.4.0)
├── puppetlabs-logentries (v0.1.0)
├── puppetlabs-nodejs (v0.8.0)
├── puppetlabs-registry (v1.1.0)
├── puppetlabs-stdlib (v4.6.0)
├── richardc-datacat (v0.6.1)
├── saz-ssh (v2.8.1)
└── serverdensity-serverdensity_agent (v0.9.5)
```

Fixed this by pip uninstall  and installing 
pip install meld3==1.0.0

**Comment by ajcrowe** [comment]
This is strange, pip should be taking care of getting all the dependencies supervisor requires in place.

I'm not sure this is a bug with the module per se.

**Comment by ajcrowe** [comment]
Closing as invalid
